version: '3.8'

services:
  # --- 1. INFRAESTRUTURA DE MENSAGERIA (KAFKA) ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # ⚙️ Configurações para garantir as 3 partições padrão por tópico
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  # --- 2. INFRAESTRUTURA DE ARMAZENAMENTO (HADOOP HDFS) ---
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false

  # --- 3. PRODUTOR (SPRING BOOT - JAVA) ---
  producer-spring:
    build: ./transaction.producer
    container_name: producer-spring
    depends_on:
      - kafka

  # --- 4. MICROSSERVIÇOS DE PROCESSAMENTO (PYTHON LEVE) ---
  # Serviço 1: Lê de 'transacoes.brutas' e distribui entre 'transacoes.ok' e 'transacoes.fraud'
  fraud-router:
    build: ./router.app
    container_name: service-fraud-router
    depends_on:
      - kafka
    restart: always

  # Serviço 2: Lê apenas 'transacoes.fraud' e dispara os alertas no n8n
  n8n-notifier:
    build: ./notifier.app
    container_name: service-n8n-notifier
    depends_on:
      - kafka
      - fraud-router
    restart: always

  # Serviço 3: Lê 'transacoes.ok' e grava no HDFS em lote
  hdfs-writer:
    build: ./hdfs_writer
    container_name: service-hdfs-writer
    depends_on:
      - kafka
      - namenode
    restart: always

  # --- 5. ORQUESTRADOR E IA (N8N) ---
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-orchestrator
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - n8n-notifier

volumes:
  n8n_data: