spring.application.name=transaction.producer
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1

# Compacta Lotes
spring.kafka.producer.compression-type=lz4

# Batching: Acumula até 64KB ou espera 20ms antes de disparar o pacote para a rede
spring.kafka.producer.properties.batch.size=65536
spring.kafka.producer.properties.linger.ms=20


# Buffer de Memória: Aumenta a fila da memória RAM para 128MB pra não travar a CPU
spring.kafka.producer.properties.buffer.memory=134217728
